version: '2'
services:
  db:
    image: 'postgres:16.4-bullseye'
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
volumes:
  db-data: